//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Lodochniki.AppDataFile
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order_details
    {
        public int Detail_ID { get; set; }
        public int Accessory_ID { get; set; }
        public int Order_ID { get; set; }
    
        public virtual Accessory Accessory { get; set; }
        public virtual Order Order { get; set; }
    }
}
